extends Node3D
"res://NOMADZ-O/P1/AdvancedCharacter/advanced_character_3d.gd"
"res://NOMADZ-O/P1/AdvancedCharacter/RIGID/rigid_player.gd"
"res://NOMADZ-O/P1/AdvancedCharacter/script_templates/AdvancedCharacter3D/basic_movement.gd"
"res://NOMADZ-O/PLAYER-1/addons/playercharacter3d_template/custom_classes/playercharacter3d_class.gd"
"res://NOMADZ-O/PLAYER-1/addons/playercharacter3d_template/script_templates/CharacterBody3D/wasd_movement.gd"
"res://NOMADZ-O/PLAYER-1/addons/playercharacter3d_template/add_script_templates.gd"
"res://NOMADZ-O/CONTTROLLER/flight_navigation_3d_editor_plugin.gd"
"res://NOMADZ-O/CONTTROLLER/addons/real-controller/animation.gd"
"res://NOMADZ-O/CONTTROLLER/addons/real-controller/character.gd"
